# Generated by Django 4.2.4 on 2023-08-24 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0002_alter_userfollows_lecteur_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="texte",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="titre",
            new_name="headline",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="note",
            new_name="rating",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="date",
            new_name="time_created",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="lecteur",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="date",
            new_name="time_created",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="titre",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="lecteur",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userfollows",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userfollows",
            name="followed_user",
            field=models.ForeignKey(
                default=2023,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfollows",
            name="user",
            field=models.ForeignKey(
                default=2023,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="userfollows",
            unique_together={("user", "followed_user")},
        ),
        migrations.RemoveField(
            model_name="userfollows",
            name="lecteur",
        ),
        migrations.RemoveField(
            model_name="userfollows",
            name="lecteur_suivi",
        ),
    ]
