# Generated by Django 4.2.4 on 2023-08-28 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_alter_review_body_alter_review_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollows",
            name="followed_user_search",
            field=models.CharField(default="", max_length=128, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Note",
            ),
        ),
    ]
