# Generated by Django 4.2.4 on 2023-08-29 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0006_remove_userfollows_followed_user_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Ticket",
                to="review.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="userfollows",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Taper les premières lettres du nom d'utilisateur",
            ),
        ),
    ]
