# Generated by Django 4.2.4 on 2023-08-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_userfollows_lecteur_and_more"),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="users_followed",
            field=models.ManyToManyField(
                blank=True, null=True, to="review.userfollows"
            ),
        ),
    ]
