# Generated by Django 4.2.4 on 2023-08-22 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_users_followed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="users_followed",
        ),
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="suit"
            ),
        ),
    ]
