# Generated by Django 4.2.4 on 2023-08-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_userfollows_lecteur_and_more"),
        ("authentication", "0005_remove_user_follows_user_users_followed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="users_followed",
            field=models.ManyToManyField(to="review.userfollows"),
        ),
    ]
