# Generated by Django 4.2.4 on 2023-08-23 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_user_users_followed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="users_followed",
        ),
    ]
