# Generated by Django 4.2.4 on 2023-08-24 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_user_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follows",
        ),
    ]
